In [20]:
df_demo = pd.read_csv('../data/clean/df_final_demo.csv')
df_exp = pd.read_csv('../data/clean/df_final_experiment_clients_clean.csv')

df = df_demo.merge(df_exp, on='client_id', how='inner')

In [21]:
df['variation'].value_counts()

variation
Test       26961
Control    23526
Missing    20107
Name: count, dtype: int64

In [22]:
df.groupby('variation')[[
    'clnt_age',
    'clnt_tenure_yr',
    'num_accts',
    'bal'
]].mean()

            clnt_age  clnt_tenure_yr  num_accts            bal
variation
Control    47.498427       12.087860   2.259925  150151.900186
Missing    44.238773       12.106232   2.257920  142248.958795
Test       47.163922       11.982901   2.249917  148962.605032

In [23]:
df.groupby('variation')[[
    'clnt_age',
    'clnt_tenure_yr',
    'num_accts',
    'bal'
]].median()

           clnt_age  clnt_tenure_yr  num_accts       bal
variation
Control        48.5            11.0        2.0  66031.45
Missing        45.0            11.0        2.0  56338.10
Test           47.5            11.0        2.0  65468.36

In [24]:
df.groupby('variation')['clnt_age'].describe()

             count       mean        std   min   25%   50%   75%   max
variation
Control    23526.0  47.498427  15.521781  17.0  33.5  48.5  60.0  96.0
Missing    20107.0  44.238773  15.555909  13.5  30.5  45.0  56.5  92.5
Test       26961.0  47.163922  15.514461  17.0  33.5  47.5  59.5  96.0

In [25]:
pd.crosstab(df['variation'], df['gendr'], normalize='index')

gendr             F         M         U
variation
Control    0.320581  0.338774  0.340644
Missing    0.322624  0.337047  0.340329
Test       0.323282  0.332962  0.343756

In [26]:
df.groupby('variation')[[
    'calls_6_mnth',
    'logons_6_mnth'
]].mean()

           calls_6_mnth  logons_6_mnth
variation
Control        3.129176       6.166242
Missing        4.108619       4.147710
Test           3.061941       6.101851