In [1]:
import pandas as pd

df1 = pd.read_csv('../data/clean/df_final_experiment_clients_clean.csv')
df2 = pd.read_csv('../data/clean/clean_web_data.csv')
df3 = pd.read_csv('../data/clean/df_final_demo.csv')

In [2]:
df1.shape

(70609, 2)

In [3]:
df2.shape

(120157, 5)

In [4]:
df3.shape

(70594, 9)

In [5]:
df = df3.merge(df1, on='client_id', how='outer')

In [6]:
df.head()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,variation
0,169,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0,Missing
1,555,3.0,46.0,29.5,U,2.0,25454.66,2.0,6.0,Test
2,647,12.0,151.0,57.5,M,2.0,30525.80,0.0,4.0,Test
3,722,11.0,143.0,59.5,F,2.0,22466.17,1.0,1.0,Missing
4,934,9.0,109.0,51.0,F,2.0,32522.88,0.0,3.0,Test

In [7]:
df_final = df.merge(df2, on='client_id', how='outer')

In [8]:
df_final.shape

(120157, 14)

In [9]:
df_final.head()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,variation,visitor_id,visit_id,process_step,date_time
0,169,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0,Missing,201385055_71273495308,749567106_99161211863_557568,confirm,2017-04-12 20:23:09
1,336,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64757908_3400128256,649044751_80905125055_554468,start,2017-06-01 07:42:43
2,546,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,475037402_89828530214,731811517_9330176838_94847,confirm,2017-06-17 10:05:42
3,555,3.0,46.0,29.5,U,2.0,25454.66,2.0,6.0,Test,402506806_56087378777,637149525_38041617439_716659,confirm,2017-04-15 13:00:34
4,647,12.0,151.0,57.5,M,2.0,30525.80,0.0,4.0,Test,66758770_53988066587,40369564_40101682850_311847,confirm,2017-04-12 15:47:45

In [10]:
df_final.isnull().sum()

client_id               0
clnt_tenure_yr      49563
clnt_tenure_mnth    49563
clnt_age            49563
gendr               49563
num_accts           49563
bal                 49563
calls_6_mnth        49563
logons_6_mnth       49563
variation           49548
visitor_id              0
visit_id                0
process_step            0
date_time               0
dtype: int64

In [11]:
df_final['variation'].unique()

<StringArray>
['Missing', nan, 'Test', 'Control']
Length: 4, dtype: str

In [12]:
import numpy as np

df_final['variation'] = df_final['variation'].replace('Missing', np.nan)
df_final = df_final.dropna(subset=['variation'])

In [13]:
df_final.head()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,variation,visitor_id,visit_id,process_step,date_time
3,555,3.0,46.0,29.5,U,2.0,25454.66,2.0,6.0,Test,402506806_56087378777,637149525_38041617439_716659,confirm,2017-04-15 13:00:34
4,647,12.0,151.0,57.5,M,2.0,30525.80,0.0,4.0,Test,66758770_53988066587,40369564_40101682850_311847,confirm,2017-04-12 15:47:45
9,934,9.0,109.0,51.0,F,2.0,32522.88,0.0,3.0,Test,810392784_45004760546,7076463_57954418406_971348,start,2017-04-18 02:38:52
10,1028,12.0,145.0,36.0,M,3.0,103520.22,1.0,4.0,Control,42237450_62128060588,557292053_87239438319_391157,step_1,2017-04-08 19:00:26
12,1104,5.0,66.0,48.0,U,3.0,154643.94,6.0,9.0,Control,194240915_18158000533,643221571_99977972121_69283,start,2017-06-20 22:31:33

In [14]:
groups = df_final.groupby('variation')

df_test = groups.get_group('Test')
df_control = groups.get_group('Control')

In [36]:
df_test.info()

<class 'pandas.DataFrame'>
Index: 26968 entries, 3 to 120154
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   client_id         26968 non-null  int64
 1   clnt_tenure_yr    26961 non-null  float64
 2   clnt_tenure_mnth  26961 non-null  float64
 3   clnt_age          26961 non-null  float64
 4   gendr             26961 non-null  str
 5   num_accts         26961 non-null  float64
 6   bal               26961 non-null  float64
 7   calls_6_mnth      26961 non-null  float64
 8   logons_6_mnth     26961 non-null  float64
 9   variation         26968 non-null  str
 10  visitor_id        26968 non-null  str
 11  visit_id          26968 non-null  str
 12  process_step      26968 non-null  str
 13  date_time         26968 non-null  str
dtypes: float64(7), int64(1), str(6)
memory usage: 3.1 MB

In [37]:
df_control.info()

<class 'pandas.DataFrame'>
Index: 23532 entries, 10 to 120142
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   client_id         23532 non-null  int64
 1   clnt_tenure_yr    23526 non-null  float64
 2   clnt_tenure_mnth  23526 non-null  float64
 3   clnt_age          23526 non-null  float64
 4   gendr             23526 non-null  str
 5   num_accts         23526 non-null  float64
 6   bal               23526 non-null  float64
 7   calls_6_mnth      23526 non-null  float64
 8   logons_6_mnth     23526 non-null  float64
 9   variation         23532 non-null  str
 10  visitor_id        23532 non-null  str
 11  visit_id          23532 non-null  str
 12  process_step      23532 non-null  str
 13  date_time         23532 non-null  str
dtypes: float64(7), int64(1), str(6)
memory usage: 2.7 MB

In [ ]:
df_control.to_cvs(