In [20]:
import pandas as pd

df1 = pd.read_csv('../data/clean/df_final_experiment_clients_clean.csv')
df2 = pd.read_csv('../data/clean/fixed_web_data.csv')
df3 = pd.read_csv('../data/clean/df_final_demo.csv')

In [21]:
df1.shape

(70609, 2)

In [22]:
df2.shape

(643225, 5)

In [23]:
df3.shape

(70594, 9)

In [24]:
df = df3.merge(df1, on='client_id', how='outer')

In [25]:
df.head()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,variation
0,169,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0,Missing
1,555,3.0,46.0,29.5,U,2.0,25454.66,2.0,6.0,Test
2,647,12.0,151.0,57.5,M,2.0,30525.80,0.0,4.0,Test
3,722,11.0,143.0,59.5,F,2.0,22466.17,1.0,1.0,Missing
4,934,9.0,109.0,51.0,F,2.0,32522.88,0.0,3.0,Test

In [26]:
df_final = df.merge(df2, on='client_id', how='outer')

In [27]:
df_final.shape

(643231, 14)

In [28]:
df_final.head()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,variation,visitor_id,visit_id,process_step,date_time
0,169,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0,Missing,201385055_71273495308,749567106_99161211863_557568,start,2017-04-12 20:19:36
1,169,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0,Missing,201385055_71273495308,749567106_99161211863_557568,step_1,2017-04-12 20:19:45
2,169,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0,Missing,201385055_71273495308,749567106_99161211863_557568,step_2,2017-04-12 20:20:31
3,169,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0,Missing,201385055_71273495308,749567106_99161211863_557568,step_3,2017-04-12 20:22:05
4,169,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0,Missing,201385055_71273495308,749567106_99161211863_557568,confirm,2017-04-12 20:23:09

In [29]:
df_final.isnull().sum()

client_id                0
clnt_tenure_yr      257691
clnt_tenure_mnth    257691
clnt_age            257691
gendr               257691
num_accts           257691
bal                 257691
calls_6_mnth        257691
logons_6_mnth       257691
variation           257587
visitor_id               6
visit_id                 6
process_step             6
date_time                6
dtype: int64

In [30]:
df_final['variation'].unique()

<StringArray>
['Missing', nan, 'Test', 'Control']
Length: 4, dtype: str

In [31]:
# Dropping rows with missing values for 'variation'
import numpy as np

df_final['variation'] = df_final['variation'].replace('Missing', np.nan)
df_final = df_final.dropna(subset=['variation'])

In [32]:
df_final.info()

<class 'pandas.DataFrame'>
Index: 275382 entries, 11 to 643219
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   client_id         275382 non-null  int64
 1   clnt_tenure_yr    275289 non-null  float64
 2   clnt_tenure_mnth  275289 non-null  float64
 3   clnt_age          275289 non-null  float64
 4   gendr             275289 non-null  str
 5   num_accts         275289 non-null  float64
 6   bal               275289 non-null  float64
 7   calls_6_mnth      275289 non-null  float64
 8   logons_6_mnth     275289 non-null  float64
 9   variation         275382 non-null  str
 10  visitor_id        275378 non-null  str
 11  visit_id          275378 non-null  str
 12  process_step      275378 non-null  str
 13  date_time         275378 non-null  str
dtypes: float64(7), int64(1), str(6)
memory usage: 31.5 MB

In [23]:
# Separating control vs test
groups = df_final.groupby('variation')

df_test = groups.get_group('Test')
df_control = groups.get_group('Control')

In [34]:
df_test.info()

<class 'pandas.DataFrame'>
Index: 150288 entries, 11 to 643219
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   client_id         150288 non-null  int64
 1   clnt_tenure_yr    150237 non-null  float64
 2   clnt_tenure_mnth  150237 non-null  float64
 3   clnt_age          150237 non-null  float64
 4   gendr             150237 non-null  str
 5   num_accts         150237 non-null  float64
 6   bal               150237 non-null  float64
 7   calls_6_mnth      150237 non-null  float64
 8   logons_6_mnth     150237 non-null  float64
 9   variation         150288 non-null  str
 10  visitor_id        150285 non-null  str
 11  visit_id          150285 non-null  str
 12  process_step      150285 non-null  str
 13  date_time         150285 non-null  str
dtypes: float64(7), int64(1), str(6)
memory usage: 17.2 MB

In [35]:
df_control.info()

<class 'pandas.DataFrame'>
Index: 125094 entries, 50 to 643160
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   client_id         125094 non-null  int64
 1   clnt_tenure_yr    125052 non-null  float64
 2   clnt_tenure_mnth  125052 non-null  float64
 3   clnt_age          125052 non-null  float64
 4   gendr             125052 non-null  str
 5   num_accts         125052 non-null  float64
 6   bal               125052 non-null  float64
 7   calls_6_mnth      125052 non-null  float64
 8   logons_6_mnth     125052 non-null  float64
 9   variation         125094 non-null  str
 10  visitor_id        125093 non-null  str
 11  visit_id          125093 non-null  str
 12  process_step      125093 non-null  str
 13  date_time         125093 non-null  str
dtypes: float64(7), int64(1), str(6)
memory usage: 14.3 MB

In [36]:
df_test.to_csv('df_test_updated.csv', index=False)
df_control.to_csv('df_control_updated.csv', index=False)

In [37]:
df_test.describe()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,num_accts,bal,calls_6_mnth,logons_6_mnth
count,1.502880e+05,150237.000000,150237.000000,150237.000000,150237.000000,1.502370e+05,150237.000000,150237.000000
mean,5.005382e+06,12.127718,151.575517,48.464603,2.254658,1.606002e+05,3.177400,6.217636
std,2.877833e+06,6.927038,82.798612,15.680579,0.533435,3.681494e+05,2.199643,2.185098
min,5.550000e+02,2.000000,33.000000,17.000000,1.000000,2.378944e+04,0.000000,3.000000
25%,2.510327e+06,6.000000,82.000000,34.500000,2.000000,4.048938e+04,1.000000,4.000000
50%,5.061136e+06,11.000000,136.000000,50.000000,2.000000,6.816223e+04,3.000000,6.000000
75%,7.465587e+06,16.000000,193.000000,61.000000,2.000000,1.494577e+05,6.000000,9.000000
max,9.999832e+06,55.000000,669.000000,96.000000,7.000000,1.632004e+07,6.000000,9.000000

In [38]:
df_control.describe()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,num_accts,bal,calls_6_mnth,logons_6_mnth
count,1.250940e+05,125052.000000,125052.000000,125052.000000,125052.000000,1.250520e+05,125052.000000,125052.000000
mean,5.013098e+06,12.126843,151.507549,48.033466,2.273622,1.577408e+05,3.247233,6.283066
std,2.868050e+06,6.978165,83.359930,15.589436,0.552325,3.035033e+05,2.186807,2.174001
min,1.028000e+03,2.000000,33.000000,17.000000,2.000000,2.378961e+04,0.000000,3.000000
25%,2.525455e+06,6.000000,81.000000,34.000000,2.000000,4.082324e+04,1.000000,4.000000
50%,5.036234e+06,11.000000,136.000000,49.500000,2.000000,6.804954e+04,3.000000,6.000000
75%,7.471029e+06,16.000000,193.000000,60.500000,2.000000,1.477964e+05,6.000000,9.000000
max,9.998921e+06,55.000000,669.000000,96.000000,7.000000,8.292996e+06,6.000000,9.000000