In [5]:
import pandas as pd

df1 = pd.read_csv('../data/clean/df_final_experiment_clients_clean.csv')
df2 = pd.read_csv('../data/clean/fixed_web_data.csv')
df3 = pd.read_csv('../data/clean/df_final_demo.csv')

In [2]:
df1.shape

(70609, 2)

In [6]:
df2.shape

(643225, 5)

In [7]:
df3.shape

(70594, 9)

In [8]:
df = df3.merge(df1, on='client_id', how='outer')

In [9]:
df.head()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,variation
0,169,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0,Missing
1,555,3.0,46.0,29.5,U,2.0,25454.66,2.0,6.0,Test
2,647,12.0,151.0,57.5,M,2.0,30525.80,0.0,4.0,Test
3,722,11.0,143.0,59.5,F,2.0,22466.17,1.0,1.0,Missing
4,934,9.0,109.0,51.0,F,2.0,32522.88,0.0,3.0,Test

In [10]:
df_final = df.merge(df2, on='client_id', how='outer')

In [11]:
df_final.shape

(643231, 14)

In [12]:
df_final.head()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,variation,visitor_id,visit_id,process_step,date_time
0,169,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0,Missing,201385055_71273495308,749567106_99161211863_557568,start,2017-04-12 20:19:36
1,169,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0,Missing,201385055_71273495308,749567106_99161211863_557568,step_1,2017-04-12 20:19:45
2,169,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0,Missing,201385055_71273495308,749567106_99161211863_557568,step_2,2017-04-12 20:20:31
3,169,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0,Missing,201385055_71273495308,749567106_99161211863_557568,step_3,2017-04-12 20:22:05
4,169,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0,Missing,201385055_71273495308,749567106_99161211863_557568,confirm,2017-04-12 20:23:09

In [13]:
df_final.isnull().sum()

client_id                0
clnt_tenure_yr      257691
clnt_tenure_mnth    257691
clnt_age            257691
gendr               257691
num_accts           257691
bal                 257691
calls_6_mnth        257691
logons_6_mnth       257691
variation           257587
visitor_id               6
visit_id                 6
process_step             6
date_time                6
dtype: int64

In [14]:
df_final['variation'].unique()

<StringArray>
['Missing', nan, 'Test', 'Control']
Length: 4, dtype: str

In [15]:
# Dropping rows with missing values for 'variation'
import numpy as np

df_final['variation'] = df_final['variation'].replace('Missing', np.nan)
df_final = df_final.dropna(subset=['variation'])

In [16]:
df_final.info()

<class 'pandas.DataFrame'>
Index: 275382 entries, 11 to 643219
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   client_id         275382 non-null  int64
 1   clnt_tenure_yr    275289 non-null  float64
 2   clnt_tenure_mnth  275289 non-null  float64
 3   clnt_age          275289 non-null  float64
 4   gendr             275289 non-null  str
 5   num_accts         275289 non-null  float64
 6   bal               275289 non-null  float64
 7   calls_6_mnth      275289 non-null  float64
 8   logons_6_mnth     275289 non-null  float64
 9   variation         275382 non-null  str
 10  visitor_id        275378 non-null  str
 11  visit_id          275378 non-null  str
 12  process_step      275378 non-null  str
 13  date_time         275378 non-null  str
dtypes: float64(7), int64(1), str(6)
memory usage: 31.5 MB

In [23]:
# Separating control vs test
groups = df_final.groupby('variation')

df_test = groups.get_group('Test')
df_control = groups.get_group('Control')

In [18]:
df_test.info()

<class 'pandas.DataFrame'>
Index: 150288 entries, 11 to 643219
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   client_id         150288 non-null  int64
 1   clnt_tenure_yr    150237 non-null  float64
 2   clnt_tenure_mnth  150237 non-null  float64
 3   clnt_age          150237 non-null  float64
 4   gendr             150237 non-null  str
 5   num_accts         150237 non-null  float64
 6   bal               150237 non-null  float64
 7   calls_6_mnth      150237 non-null  float64
 8   logons_6_mnth     150237 non-null  float64
 9   variation         150288 non-null  str
 10  visitor_id        150285 non-null  str
 11  visit_id          150285 non-null  str
 12  process_step      150285 non-null  str
 13  date_time         150285 non-null  str
dtypes: float64(7), int64(1), str(6)
memory usage: 17.2 MB

In [19]:
df_control.info()

<class 'pandas.DataFrame'>
Index: 125094 entries, 50 to 643160
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   client_id         125094 non-null  int64
 1   clnt_tenure_yr    125052 non-null  float64
 2   clnt_tenure_mnth  125052 non-null  float64
 3   clnt_age          125052 non-null  float64
 4   gendr             125052 non-null  str
 5   num_accts         125052 non-null  float64
 6   bal               125052 non-null  float64
 7   calls_6_mnth      125052 non-null  float64
 8   logons_6_mnth     125052 non-null  float64
 9   variation         125094 non-null  str
 10  visitor_id        125093 non-null  str
 11  visit_id          125093 non-null  str
 12  process_step      125093 non-null  str
 13  date_time         125093 non-null  str
dtypes: float64(7), int64(1), str(6)
memory usage: 14.3 MB

In [20]:
df_test.to_csv('df_test_updated.csv', index=False)
df_control.to_csv('df_control_updated.csv', index=False)